apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: master
  name: master
  namespace: gleam
spec:
  replicas: 1
  selector:
    matchLabels:
      service: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: master
    spec:
      containers:
        - name: master
          # image: chrislusf/gleam
          image: gleam:local
          imagePullPolicy: Never
          ports:
            - containerPort: 45326
              protocol: TCP
            - containerPort: 55326
              protocol: TCP
          args:
            - "master"
